image:
  name: docker.io/puppet/pdk:latest
  entrypoint:
    - ""

stages:
  - test

variables:
  PDK_DISABLE_ANALYTICS: 'true'
  DOCKER_HOST: 'podman:///'
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2

before_script:
  - pdk --version

unit_tests:
  stage: test
  script:
    - pdk test unit --verbose --format=junit:report.xml
  artifacts:
    reports:
      junit: report.xml
    when: on_failure
  cache:
    paths:
      - vendor/
      - .bundle/
  coverage: '/\(\d+.\d+%\) covered/'

lint:
  stage: test
  script:
    - pdk validate
  allow_failure: true
