---
.github/workflows/ci.yml:
  acceptance_tests: true
  main_branches: [ 'production' ]

.rubocop.yml:
  extra:
    Layout/LineLength:
      Max: 140
    Style/WordArray:
      EnforcedStyle: brackets
    Style/TrailingCommaInArguments:
      EnforcedStyleForMultiline: diff_comma
    Lint/RedundantDirGlobSort:
      Enabled: false

.puppet-lint.rc:
  disabled_lint_checks:
    - 80chars
    - 140chars
    - selector_inside_resource
    - parameter_documentation
  enabled_lint_checks:
    - parameter_types
