name: Generate Reference

on:
    push:
        branches: [production]

jobs:
    generate_reference:
        runs-on: ubuntu-latest
        container:
            image: docker.io/puppet/pdk:latest

        env:
            PDK_DISABLE_ANALYTICS: "true"

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Gemfile Dependencies
              run: pdk bundle install

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      vendor/
                      .bundle/
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-

            - name: Generate reference
              run: pdk bundle exec rake strings:reference:generate

            - name: Commit and Push changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add REFERENCE.md
                  git diff --staged --quiet || git commit -m "Update REFERENCE.md [skip ci]"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
